FROM ruby:3.2.6

ENV LANG=C.UTF-8 \
    TZ=Asia/Tokyo \
    BUNDLER_VERSION=2.4.10

RUN apt-get update -qq && \
    apt-get install -y curl gnupg build-essential libpq-dev git vim && \
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs && \
    corepack enable && \
    corepack prepare yarn@stable --activate && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN gem install bundler -v "${BUNDLER_VERSION}"

EXPOSE 3000
